config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'



  resources :articles

  get 'signup' => 'users#new'
  resources :users, except: [:new]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'


  resources :categories, except: [:destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user

	has_many :article_categories
	has_many :categories, through: :article_categories



	validates :title, presence: true, 
			  length: {minimum: 3, maximum: 50}

	validates :description, presence: true, 
			  length: {minimum: 10, maximum: 300}

	validates :user_id, presence: true


end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base

belongs_to :article

belongs_to :category

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories
	
	validates :name, presence: true, length: { maximum: 25, minimum: 3 }
	validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }
	validates  	:username, presence: true,
				uniqueness: { case_sensitive: true}, 
				length:{ minimum: 3, maximum: 25 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates 	:email, presence: true, length: { maximum: 105 },
				uniqueness: { case_sensitive: true}, 
				format: { with: VALID_EMAIL_REGEX }

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def logged_in?
  	!!current_user
  end


  def require_user
  	if !logged_in? 
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = "Article was successfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article was successfully updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
	end

	def destroy
		@article.destroy
		flash[:danger] = "Article was successfully deleted"
		redirect_to articles_path
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description, category_ids: [])
	end

	def require_same_user
		if current_user != @article.user and !current_user.admin?
			flash[:danger] = "You can only edit or delete your own articles"
			redirect_to root_path
		end
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except: [:index, :show]

	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end

	def show
		@category = Category.find(params[:id])
		@category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category was created successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:success]  ="Name was successfully updated"
			redirect_to category_path(@category)
		else
			render 'edit'
		end
	end

	private


	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? || (logged_in? and !current_user.admin?)
			flash[:danger] = "Only admins can perform that action"
			redirect_to categories_path
		end
	end	


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in"
			redirect_to user_path(user)
		else	
			flash.now[:danger] = "Your email or password don't match"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out!"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update ,:destroy]
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to the alpha blog #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "User and all articles created by it have been deleted"
		redirect_to users_path
	end	



	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user and !current_user.admin?
			flash[:danger] = "You can only edit your own account"
			redirect_to root_path
		end
	end

	def require_admin
		if logged_in? and !current_user.admin?
			flash[:danger] = "Only admins can perform that action"
			redirect_to root_path
		end
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = { size:80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="article-title">
				<%= link_to article.title, article_path(article)%>
			</div>
			<div class="article-body">
				<%= truncate(article.description, length: 100) %>
				<div class="article-meta-details">
					<small>Created by: <%= article.user.username if article.user %>, 
							<%= time_ago_in_words(article.created_at) %> ago,
							Last updated: <%= time_ago_in_words(article.updated_at)	%>
					</small>
				</div>
			</div>
			
			<% if article.categories.any? %>
				<p>Categories: <%= render article.categories %></p>
			<% end %>
			<% if logged_in? && (current_user == article.user || current_user.admin?) %>
			<div class="article-actions spacing">
			<%= link_to "Edit", edit_article_path(article), class: "btn btn-sm btn-warning" %>
			<%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-danger" %> 

			</div>
			<%end%>
		</div>
	</div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="panel panel-default">
	<div class="panel-body">
		<%= form_for @article do |f| %>

		<div class="form-group">
			<%= f.label :title %> 
			<%= f.text_field :title, class: "form-control", placeholder: "Title of your article" %>
		</div>


		<div class="form-group">
			<%= f.label :description %> 
			<%= f.text_area :description, class: "form-control", placeholder: "Description of your article" %>
		</div>


		<div class="form-group">
			<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
			<% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
			<% end %>
		</div>


		<%= f.submit class: "btn btn-success btn-md"%>

		<% end %>

		<%= link_to "Back", articles_path, class: "btn btn-default spacing" %>
	</div>
</div>

app/views/articles/edit.html.erb
<div class="panel-heading"><h1 style="text-align:center"> Edit this article </h1></div>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>


<div align="center">
	<%= will_paginate @articles, renderer: BootstrapPagination::Rails%>
</div>

<%= render 'article', obj: @articles%>

<div align="center">
	<%= will_paginate @articles, renderer: BootstrapPagination::Rails%>
</div>

app/views/articles/new.html.erb
<div class="panel-heading"><h1 style="text-align:center"> Create an Article </h1></div>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> Title: <%= @article.title %></h2>

<div class="well">
	<% if @article.user %>
	<ul class="listing" align="center">
		<div class="row" >
			<div class="col-md-4 col-md-offset-4">
				<li> <h4>Created by: </h4></li>
				<div class="well well-lg">
					<li>
						<%= link_to gravatar_for(@article.user), user_path(@article.user)  %>
					</li>
					<li class="article-title">
						<%= link_to @article.user.username, user_path(@article.user) %>
					</li>
					<li>
						<small>
							<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
						</small>
					</li>
				</div>
			</div>
		</div>
	</ul>
	<%end%>
	<h4 align="center"><strong>Description</strong></h4>
	<hr>
	<%= simple_format(@article.description) %>

	<% if @article.categories.any? %>
		<p> Categories: <%= render @article.categories %></p>	
	<% end %>



<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
<div class="article-actions">
<%= link_to "Edit", edit_article_path(@article), class: "btn btn-md btn-warning" %> 
<%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-md btn-danger" %>

<%end%>
<%= link_to "View all", articles_path,  class: "btn btn-md btn-default" %>

</div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h2 align="center"> Create Category </h2>
	</div>
	<div class="panel-body">
		<%= form_for @category do |f| %>

		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control" %> 
		</div>

		<div class="form-group">
			<%= f.submit class: "btn btn-success btn-md" %>

		</div>

		<% end %>

	</div>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category name </h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing all Categories</h1>
<div align="center">
<div align="center">
	<%= will_paginate @categories, renderer: BootstrapPagination::Rails%>
</div>
	<% @categories.each do |category| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li class="article-title">
						<%= link_to "#{category.name}", category_path(category) %>
					</li>
					<li><small><%= pluralize(category.articles.count, "article") %></small></li>
				</div>
			</div>
		</ul>
	<% end %>
<div align="center">
	<%= will_paginate @categories, renderer: BootstrapPagination::Rails%>
</div>
</div>

app/views/categories/new.html.erb
<%= render 'shared/errors', obj: @category %>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<% if logged_in? and current_user.admin? %>

<div align="center">
<span class="badge"><%= link_to "Edit category name", edit_category_path(@category)%></span>
</div></br>
<% end %>
<div align="center">
	<%= will_paginate @category_articles, renderer: BootstrapPagination::Rails%>
</div>

<%= render 'articles/article', obj: @category_articles %>

<div align="center">
	<%= will_paginate @category_articles, renderer: BootstrapPagination::Rails%>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="#{}">Alpha-Blog</a>
			by <a href="www.jan-lucapfeiffer.de">Jan-Luca Pfeiffer</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
			</ul> 

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	
<div class='alert alert-<%="#{name}"%>'>
	<a href="#" ></a>
	<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default ">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha-Blog", root_path, class: "navbar-brand"%>
    </div>

    <div class="collapse navbar-collapse navbar-left" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Articles", articles_path %>
        </li>
         <li>
          <%= link_to "Users", users_path %>
        </li>
        <% if logged_in? %>
        <li>
          <%= link_to "New article", new_article_path %>
        </li>
        <% end %>
         
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
            Categories
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "All Categories", categories_path %>
            </li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category)%></li>
            <% end %>
            

            <% if logged_in? and current_user.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create Category", new_category_path %></li>
            <% end %>
            
          </ul>
      </div>

    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li>
            <%= link_to "Log Out", logout_path, method: :delete %>
          </li>

          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> 
            Your Profile <%= "Admin" if current_user.admin? %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Edit your profile", edit_user_path(current_user) %>
            </li>
            <li>
              <%= link_to "View your profile", user_path(current_user) %>
            </li>
            
          </ul>
        </li>
        <% end %>
        <% if !logged_in? %>
          <li>
            <%= link_to "Login", login_path %>
          </li>
        
        <% end %> 
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<h1> Say hi to about </h1>
<h2> Also wants bootstrap so bad! </h2>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron" style="text-align:center">
	<h1> Alpha-Blog </h1>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-info btn-lg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger panel-body" role="alert">
	<h2 class="panel-title" style="text-align:center" > The following errors occured </h2><%= pluralize(obj.errors.count, "error") %>
		<ul>
			<% obj.errors.full_messages.each do |msg|%>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="panel panel-default">
<div class="panel-heading">
	<h2> Sign up for Alpha-Blog </h2>
</div>
	<div class="panel-body">
		<%= form_for @user do |f| %>

		<div class="form-group">
			<%= f.label :username %> 
			<%= f.text_field :username, class: "form-control", placeholder: "Enter username" %>
		</div>

		<div class="form-group">
			<%= f.label :email %> 
			<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
		</div>

		<div class="form-group">
			<%= f.label :password %> 
			<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
		</div>

		<%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-success btn-md")%>

		<% end %>

		<%= link_to "Back", articles_path, class: "btn btn-sm btn-default spacing" %>
	</div>
</div>

app/views/users/edit.html.erb
<h2 align="center">Edit your account</h2

<%= render 'form' %>

app/views/users/index.html.erb
<h2 align="center"> All Alpha-Blog users </h2>

<% @users.each do |user| %>
<div align="center">
	<%= will_paginate @users, renderer: BootstrapPagination::Rails%>
	<ul class="listing">
		<div class="row" >
			<div class="col-md-4 col-md-offset-4">
				<div class="well well-lg">
					<li>
						<%= link_to gravatar_for(user), user_path(user) %>
					</li>
					<li class="article-title">
						<%= link_to user.username, user_path(user) %>
					</li>
					<li>
						<small>
							<%= pluralize(user.articles.count, "article") if user.articles %>
						</small>
					</li>
					<% if logged_in? and current_user.admin? %>
						<li>

							<%= link_to "Delete user", user_path(user), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Are you sure you wanna do that?"} %>
                        </li>
					<% end %>
				</div>
			</div>
		</div>
	</ul>
	<%= will_paginate @users, renderer: BootstrapPagination::Rails%>
</div>

<% end %>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>

<%= render 'form' %>

app/views/users/show.html.erb
<h2 align="center"> Welcome to <%= @user.username %>'s page </h2>

<div class="row">
	<div class="col-md-4 col-md-offset-4" style="text-align:center">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>

<h4 align="center"><%= @user.username%>'s articles</h4>

<div align="center">
	<%= will_paginate @user_articles , renderer: BootstrapPagination::Rails %>
</div>

<%= render 'articles/article', obj: @user_articles %>

<div align="center">
	<%= will_paginate @user_articles , renderer: BootstrapPagination::Rails %>
</div>